services:
  webserver:
    image: rohitrawat891997/webserver123:latest
    ports:
      - 80:80
    environment: 
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_USER: root
        MYSQL_HOST: mysql
        MYSQL_DB: customer_db
    networks:
      - twotier
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.6
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DB: customer_db
    networks:
      - twotier
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql  


networks:
  twotier:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
