apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: db
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-container
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-secrets
              key: mypass
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: db
          mountPath: /var/lib/mysql
      volumes:
      - name: init-sql
        configMap:
          name: mysql-initdb
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
