apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    role: web
spec:
  containers:
  - name: webserver
    image: rohitrawat891997/webserver123:latest
    ports:
    - containerPort: 80
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: web-secrets
          key: mypass
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: web-secrets
          key: myuser
    - name: MYSQL_HOST
      value: mysql
    - name: MYSQL_DB
      value: customer_db
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
