apiVersion: v1
kind: Service
metadata:
  labels:
    role: web
  name: web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    role: web
  type: NodePort
status:
  loadBalancer: {}
